"use client";
import { Download, FileX2 } from "lucide-react";
export function Panel({ title, subtitle, children, action }: any) { return <section className="mb-4 rounded-[1.75rem] bg-white p-4 shadow-[0_14px_32px_rgba(15,23,42,0.06)]"><div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="text-base font-black text-slate-900">{title}</h3>{subtitle && <p className="mt-1 text-xs font-semibold text-slate-400">{subtitle}</p>}</div>{action}</div>{children}</section>; }
export function Stat({ label, value, icon, tone="teal", sub }: any) { const tones:any={teal:"from-[#0f8f7d] to-[#0b6f62]",blue:"from-blue-600 to-blue-800",orange:"from-amber-500 to-orange-600",purple:"from-purple-600 to-purple-800",slate:"from-slate-700 to-slate-900",rose:"from-rose-500 to-red-700",emerald:"from-emerald-600 to-emerald-800"}; return <div className={`relative overflow-hidden rounded-[1.55rem] bg-gradient-to-br ${tones[tone]||tones.teal} p-4 text-white shadow-lg`}><div className="absolute -left-8 -top-8 h-24 w-24 rounded-full bg-white/10"/><div className="relative flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold text-white/75">{label}</p><div className="mt-1 break-words text-xl font-black leading-7">{value}</div>{sub&&<p className="mt-1 text-[10px] font-bold text-white/70">{sub}</p>}</div>{icon&&<div className="shrink-0 rounded-2xl bg-white/15 p-2">{icon}</div>}</div></div>; }
export function Avatar({ url, name, size="md" }: any) { const cls=size==="lg"?"h-20 w-20 text-2xl":size==="sm"?"h-10 w-10 text-sm":"h-12 w-12 text-base"; return <div className={`${cls} shrink-0 overflow-hidden rounded-2xl bg-[#0f8f7d] text-white shadow-sm`}>{url?<img src={url} alt={name||"avatar"} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center font-black">{String(name||"م").slice(0,1)}</div>}</div>; }
export function InfoCard({ title, subtitle, meta, status, footer, avatar }: any) { return <article className="mb-3 rounded-[1.35rem] border border-slate-100 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3">{avatar}<div className="min-w-0"><h4 className="break-words text-sm font-black text-slate-900">{title}</h4>{subtitle&&<p className="mt-1 line-clamp-3 break-words text-xs font-bold leading-5 text-slate-500">{subtitle}</p>}</div></div>{status}</div>{meta?.length?<div className="mt-3 grid grid-cols-2 gap-2">{meta.map((m:any)=><div key={m.label} className={`rounded-2xl bg-white px-3 py-2 ${m.wide?"col-span-2":""}`}><p className="text-[10px] font-black text-slate-400">{m.label}</p><p className={`${m.wide?"whitespace-normal break-all text-right":"truncate"} mt-1 text-xs font-black text-slate-700`}>{m.value||"-"}</p></div>)}</div>:null}{footer&&<div className="mt-3">{footer}</div>}</article>; }
export function Status({ value }: any) { const styles:any={pending:"bg-amber-50 text-amber-700",arrived:"bg-emerald-50 text-emerald-700",completed:"bg-blue-50 text-blue-700",cancelled:"bg-red-50 text-red-700"}; const labels:any={pending:"منتظر",arrived:"تم الاستقبال",completed:"مكتمل",cancelled:"ملغي"}; return <span className={`shrink-0 rounded-full px-3 py-1 text-[11px] font-black ${styles[value]||"bg-slate-100 text-slate-600"}`}>{labels[value]||value||"-"}</span>; }
export function Empty({ text="لا توجد بيانات." }: any) { return <p className="rounded-2xl bg-slate-50 px-4 py-8 text-center text-sm font-bold text-slate-400">{text}</p>; }
export function Input(props:any) { return <input {...props} className={`h-12 w-full rounded-2xl bg-slate-50 px-4 text-sm font-bold text-slate-700 outline-none ${props.className||""}`}/>; }
export function Select(props:any) { return <select {...props} className={`h-12 w-full rounded-2xl bg-slate-50 px-4 text-sm font-bold text-slate-700 outline-none ${props.className||""}`}/>; }
export function Textarea(props:any) { return <textarea {...props} className={`min-h-24 w-full rounded-2xl bg-slate-50 px-4 py-3 text-sm font-bold text-slate-700 outline-none ${props.className||""}`}/>; }
export function DownloadButton({ onClick, label="تنزيل الملف" }: any) { return <button onClick={onClick} className="flex h-11 w-full items-center justify-center gap-2 rounded-2xl bg-slate-900 text-xs font-black text-white"><Download size={16}/>{label}</button>; }
export function NoFile() { return <div className="flex items-center justify-center gap-2 rounded-2xl bg-slate-100 px-3 py-3 text-xs font-black text-slate-400"><FileX2 size={16}/> لا يوجد مرفق</div>; }
export function Modal({ open, title, message, onClose, onConfirm, confirmText="تأكيد" }: any) { if(!open)return null; return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-900/40 p-3" dir="rtl"><div className="w-full max-w-[430px] rounded-[2rem] bg-white p-5 shadow-2xl"><h3 className="text-lg font-black text-slate-900">{title}</h3><p className="mt-2 text-sm font-bold leading-7 text-slate-500">{message}</p><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={onClose} className="h-12 rounded-2xl bg-slate-100 text-sm font-black text-slate-600">إلغاء</button><button onClick={onConfirm} className="h-12 rounded-2xl bg-[#0f8f7d] text-sm font-black text-white">{confirmText}</button></div></div></div>; }
